# Reusable in-cluster demo bootstrapper.
# Build: podman build -t quay.io/aarrichi/rh-demo-bootstrapper:ubi9-1 -f Containerfile .
FROM registry.access.redhat.com/ubi9/ubi:9.6

ARG OC_MIRROR=https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz

USER 0

RUN dnf install -y --setopt=install_weak_deps=False \
      git \
      python3 \
      python3-pip \
      python3-devel \
      gcc \
      gcc-c++ \
      make \
      openssl \
      tar \
      gzip \
      jq \
      rsync \
    && dnf clean all \
    && curl -fsSL "${OC_MIRROR}" -o /tmp/oc.tar.gz \
    && tar -xzf /tmp/oc.tar.gz -C /usr/local/bin oc kubectl \
    && chmod 0755 /usr/local/bin/oc /usr/local/bin/kubectl \
    && rm -f /tmp/oc.tar.gz \
    && mkdir -p /work \
    && (getent passwd 1001 >/dev/null || useradd -u 1001 -g 0 -d /work -M -s /bin/bash demo) \
    && chown -R 1001:0 /work \
    && chmod -R g=u /work

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 0755 /usr/local/bin/entrypoint.sh

ENV HOME=/work \
    WORK_DIR=/work

WORKDIR /work
USER 1001

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
