apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: prefix-cache-lab
  namespace: prefix-cache-lab
  labels:
    app: prefix-cache-lab
    app.kubernetes.io/part-of: llm-d-demolab
spec:
  lookupPolicy:
    local: true
