apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prefix-cache-lab
  namespace: prefix-cache-lab
  labels:
    app: prefix-cache-lab
  annotations:
    haproxy.router.openshift.io/timeout: 300s
spec:
  to:
    kind: Service
    name: prefix-cache-lab
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
